Repository team-hermez/farrot, pull requests merged in 2024-09, with the labels that each got.

#2 feat build 추가
  build.gradle
Labels: ⚙ Setting

#3 알림 페이지 생성 및 헤더 수정
  src/main/java/com/hermez/farrot/notification/controller/NotificationController.java
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/notification/notification-list.html
Labels: ✨ Feature

#4 인덱스 경로 수정
  src/main/java/com/hermez/farrot/index/IndexController.java
Labels: 🐞 BugFix

#5 알림 커밋 추가
  src/main/java/com/hermez/farrot/notification/controller/NotificationController.java
Labels: 🐞 BugFix

#6 회원 관련 기능 추가
  src/main/java/com/hermez/farrot/config/SecurityConfig.java
  src/main/java/com/hermez/farrot/member/controller/MemberController.java
  src/main/java/com/hermez/farrot/member/dto/request/MemberRegisterRequest.java
  src/main/java/com/hermez/farrot/member/entity/CustomUser.java
  src/main/java/com/hermez/farrot/member/entity/Member.java
  src/main/java/com/hermez/farrot/member/entity/Role.java
  src/main/java/com/hermez/farrot/member/repository/MemberRepository.java
  src/main/java/com/hermez/farrot/member/service/UserDetailsServiceImpl.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/register.html
Labels: ✨ Feature

#8 fix: MemberRepository 수정
  src/main/java/com/hermez/farrot/member/repository/MemberRepository.java
Labels: 🥰 Accessibility

#9 fix: UserService 수정
  src/main/java/com/hermez/farrot/member/service/UserService.java
Labels: 🐞 BugFix

#10 상품 등록/수정/삭제 구현
  src/main/java/com/hermez/farrot/category/entity/Category.java
  src/main/java/com/hermez/farrot/category/repository/CategoryRepository.java
  src/main/java/com/hermez/farrot/category/service/CategoryService.java
  src/main/java/com/hermez/farrot/category/service/impl/CategoryServiceImpl.java
  src/main/java/com/hermez/farrot/product/controller/ProductController.java
  src/main/java/com/hermez/farrot/product/dto/request/ProductsSearchRequest.java
  src/main/java/com/hermez/farrot/product/dto/response/ProductDetailResponse.java
  src/main/java/com/hermez/farrot/product/entity/Product.java
  src/main/java/com/hermez/farrot/product/entity/ProductStatus.java
  src/main/java/com/hermez/farrot/product/repository/ProductRepository.java
  src/main/java/com/hermez/farrot/product/repository/ProductStatusRepository.java
  src/main/java/com/hermez/farrot/product/service/ProductService.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
  src/main/java/com/hermez/farrot/util/PriceFormatUtil.java
  src/main/resources/templates/product/product-detail.html
  src/main/resources/templates/product/products.html
  src/main/resources/templates/product/register-sell.html
  src/main/resources/templates/product/update-sell.html
Labels: ✨ Feature

#11 feat chat 관련 추가
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/request/BeforeChatRequest.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/request/SendMessageRequest.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatRoomResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/LatestMessageResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/SenderType.java
  src/main/java/com/hermez/farrot/chat/chatmessage/entity/ChatMessage.java
  src/main/java/com/hermez/farrot/chat/chatmessage/entity/ChatMessageType.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/query/ChatMessageQueryRepository.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/request/ChatRoomRequest.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/response/ChatRoomsResponse.java
  src/main/java/com/hermez/farrot/chat/chatroom/entity/ChatRoom.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/hermez/farrot/config/FirebaseConfig.java
  src/main/java/com/hermez/farrot/config/WebSocketConfig.java
  src/main/resources/templates/chat/chat-room.html
  src/main/resources/templates/chat/chat-rooms.html
Labels: ✨ Feature

#15 멤버별 상품 불러오기 구현
  src/main/java/com/hermez/farrot/product/repository/ProductRepository.java
  src/main/java/com/hermez/farrot/product/service/ProductService.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
Labels: ✨ Feature

#16 chat 구현중
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
Labels: ✨ Feature

#17 상품 상태 TableName 추가
  src/main/java/com/hermez/farrot/product/entity/Product.java
  src/main/java/com/hermez/farrot/product/entity/ProductStatus.java
Labels: 🐞 BugFix

#19 chat 상대방 구분 가능
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatResponse.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/resources/templates/chat/chat-room.html
  src/main/resources/templates/product/product-detail.html
Labels: ✨ Feature

#20 feat image 이미지 관련 기능 추가
  src/main/java/com/hermez/farrot/image/controller/ImageController.java
  src/main/java/com/hermez/farrot/image/dto/request/ImageRequest.java
  src/main/java/com/hermez/farrot/image/entity/Image.java
  src/main/java/com/hermez/farrot/image/exception/ImageProcessionException.java
  src/main/java/com/hermez/farrot/image/repository/ImageRepository.java
  src/main/java/com/hermez/farrot/image/service/FirebaseService.java
  src/main/java/com/hermez/farrot/image/service/ImageService.java
Labels: ✨ Feature

#22 chat 이전 대화 불러오기 추가
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatRoomResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/response/ChatRoomEnterResponse.java
  src/main/resources/templates/chat/chat-room.html
Labels: ✨ Feature

#23 관리자 페이지 생성
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepository.java
  src/main/resources/templates/admin/admin-contacts.html
  src/main/resources/templates/admin/admin-form.html
  src/main/resources/templates/admin/admin-sidebar.html
Labels: ✨ Feature

#24 view 0->1 설정
  src/main/java/com/hermez/farrot/product/entity/Product.java
Labels: ✨ Feature

#25 chat 기능 구현중
  src/main/java/com/hermez/farrot/chat/StompHandler.java
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/request/SendMessageRequest.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatRoomResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/request/ChatRoomRequest.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/response/ChatRoomEnterResponse.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/response/ChatRoomsResponse.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/hermez/farrot/config/WebSocketConfig.java
  src/main/resources/templates/chat/chat-room.html
  src/main/resources/templates/chat/chat-rooms.html
  src/main/resources/templates/product/product-detail.html
Labels: ✨ Feature

#27 chat 관련 repository spring data jpa로 리팩토링
  src/main/java/com/hermez/farrot/chat/CustomHandshakeInterceptor.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
Labels: 🔨 Refactor

#28 상품 이미지 구현
  src/main/java/com/hermez/farrot/image/repository/ImageRepository.java
  src/main/java/com/hermez/farrot/image/service/ImageService.java
  src/main/java/com/hermez/farrot/product/controller/ProductController.java
  src/main/java/com/hermez/farrot/product/dto/request/ProductSearchRequest.java
  src/main/java/com/hermez/farrot/product/dto/request/ProductsSearchRequest.java
  src/main/java/com/hermez/farrot/product/dto/response/ProductDetailResponse.java
  src/main/java/com/hermez/farrot/product/dto/response/ProductSearchResponse.java
  src/main/java/com/hermez/farrot/product/dto/response/ProductWithImage.java
  src/main/java/com/hermez/farrot/product/service/ProductService.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
  src/main/resources/static/default-product-image.png
  src/main/resources/templates/product/product-detail.html
  src/main/resources/templates/product/products.html
  src/main/resources/templates/product/register-sell.html
Labels: ✨ Feature

#29 어드민 차트 구현중
  src/main/resources/static/js/chart/chart.js
  src/main/resources/templates/admin/admin-form.html
Labels: ✨ Feature

#30 chat 관련 쿼리 수정중
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/request/SendMessageRequest.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/LatestMessageResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/query/ChatMessageQueryRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/request/ChatRoomRequest.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomCustomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
Labels: 🔨 Refactor

#31 관리자 멤버 관리 페이지 생성
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/templates/admin/admin-contacts.html
  src/main/resources/templates/admin/admin-form.html
  src/main/resources/templates/admin/admin-member.html
  src/main/resources/templates/admin/admin-sidebar.html
Labels: ✨ Feature, 🔨 Refactor

#32 관리자 사이드바 및 상단 생성
  src/main/resources/templates/admin/admin-contacts.html
  src/main/resources/templates/admin/admin-form.html
  src/main/resources/templates/admin/admin-member.html
  src/main/resources/templates/admin/admin-sidebar.html
  src/main/resources/templates/admin/admin-top.html
Labels: 🔨 Refactor, 🎨 Html&css

#33 chat 페이징 기능 추가
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/request/SendMessageRequest.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/ChatResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/LatestMessageResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/SelectOption.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomCustomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
  src/main/resources/templates/chat/chat-rooms.html
Labels: ✨ Feature

#34 refactor chat 코드 정리
  src/main/java/com/hermez/farrot/chat/chatmessage/dto/response/LatestMessageResponse.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/SelectOption.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
  src/main/resources/templates/chat/chat-rooms.html
Labels: 🔨 Refactor

#36 notification 채팅 상대방 비로그인 상태 처리
  src/main/java/com/hermez/farrot/chat/StompHandler.java
  src/main/java/com/hermez/farrot/notification/service/FcmService.java
Labels: 🐞 BugFix

#37 관리자 사이드바 및 회원 관리 수정
  src/main/resources/templates/admin/admin-member.html
  src/main/resources/templates/admin/admin-sidebar.html
Labels: 🎨 Design

#38 관리자 메인폼 수정
  src/main/resources/templates/admin/admin-form.html
Labels: 🎨 Design

#40 refactor chat 코드 정리
  src/main/java/com/hermez/farrot/chat/StompHandler.java
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/entity/ChatMessage.java
  src/main/java/com/hermez/farrot/chat/chatmessage/exception/NoMatchUniqueReceiverException.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/SelectOption.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
  src/main/java/com/hermez/farrot/common/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#41 관리자폼 카테고리 판매 상위 5개 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/dto/AdminCategorySalesTop5Response.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepository.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/static/js/admin/categoryTop5.js
  src/main/resources/static/js/chart/chart.js
  src/main/resources/templates/admin/admin-form.html
Labels: ✨ Feature, 🎨 Design

#42 관리자 사이드바 및 컨트롤러 수정
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/resources/templates/admin/admin-member-form.html
  src/main/resources/templates/admin/admin-member.html
  src/main/resources/templates/admin/admin-sidebar.html
Labels: ✨ Feature

#44 feat chat 상품 리스트에서 채팅하러 가기 링크 처리
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/resources/static/js/chat/enterChat.js
  src/main/resources/templates/chat/chat-room.html
  src/main/resources/templates/product/products.html
Labels: ✨ Feature

#46 관리자 상품관리 페이징
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/templates/admin/product/admin-product-monthly.html
  src/main/resources/templates/admin/product/admin-product-today.html
  src/main/resources/templates/admin/product/admin-product-weekly.html
  src/main/resources/templates/admin/product/admin-product.html
Labels: ✨ Feature

#47 관리자 멤버관리 페이징 및 페이지 생성
  src/main/java/com/hermez/farrot/admin/repository/AdminRepository.java
  src/main/resources/templates/admin/admin-sidebar.html
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/form/admin-member-form.html
  src/main/resources/templates/admin/member/admin-member.html
  src/main/resources/templates/admin/member/admin-report.html
Labels: ✨ Feature, 🎨 Design

#48 관리자 메인 날씨 위젯 추가
  src/main/resources/static/js/admin/weather.js
  src/main/resources/templates/admin/admin-weather.html
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/member/admin-member.html
Labels: ✨ Feature, 📬 API

#49 관리자 회원 상세페이지 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/templates/admin/member/admin-member-detail.html
  src/main/resources/templates/admin/member/admin-member-disable.html
  src/main/resources/templates/admin/member/admin-member-trans-detail.html
Labels: ✨ Feature

#50 관리자 레이아웃 수정
  src/main/resources/templates/admin/admin-sidebar.html
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/member/admin-member.html
  src/main/resources/templates/admin/member/admin-report.html
  src/main/resources/templates/admin/product/admin-product-monthly.html
  src/main/resources/templates/admin/product/admin-product-today.html
  src/main/resources/templates/admin/product/admin-product-weekly.html
  src/main/resources/templates/admin/product/admin-product.html
Labels: 🎨 Design

#51 관리자 일주일 가입 차트 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/dto/AdminRegisterWeeklyResponse.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/static/js/admin/registerWeekly.js
  src/main/resources/templates/admin/form/admin-form.html
Labels: ✨ Feature

#52 상품 등록 이미지 추가
  build.gradle
  src/main/java/com/hermez/farrot/image/entity/Image.java
  src/main/java/com/hermez/farrot/product/controller/ProductController.java
  src/main/java/com/hermez/farrot/product/dto/request/ProductByCategorySearchRequest.java
  src/main/java/com/hermez/farrot/product/dto/request/ProductSearchRequest.java
  src/main/java/com/hermez/farrot/product/dto/request/ProductsSearchRequest.java
  src/main/java/com/hermez/farrot/product/dto/response/ProductDetailResponse.java
  src/main/java/com/hermez/farrot/product/dto/response/ProductWithImage.java
  src/main/java/com/hermez/farrot/product/entity/Product.java
  src/main/java/com/hermez/farrot/product/repository/ProductRepository.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
  src/main/resources/templates/product/product-detail.html
Labels: ✨ Feature

#54 관리자 상세페이지 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
Labels: ✨ Feature

#56 관리자 월별 매출 차트 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/dto/AdminProductMonthTotalSalesResponse.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/static/js/admin/monthTotalSales.js
  src/main/resources/templates/admin/product/admin-product-monthly.html
Labels: ✨ Feature

#58 Fix/member/social
  src/main/java/com/hermez/farrot/member/entity/Member.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
Labels: 🐞 BugFix

#59 Fix/member
  src/main/java/com/hermez/farrot/member/entity/Member.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
Labels: 🐞 BugFix

#60 관리자 레포 타입 변경
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
Labels: 🐞 BugFix

#61 채팅 접속자수 초기화 숫자 변경
  src/main/java/com/hermez/farrot/chat/chatroom/entity/ChatRoom.java
Labels: 🐞 BugFix

#62 관리자 html 변경
  src/main/resources/templates/admin/member/admin-member-detail.html
  src/main/resources/templates/admin/member/admin-member-disable.html
  src/main/resources/templates/admin/member/admin-member.html
Labels: 🐞 BugFix

#63 fix : Member
  src/main/java/com/hermez/farrot/member/entity/Member.java
Labels: 🐞 BugFix

#64 채팅방 리스트에 안읽은 메시지 수 표시 추가
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepository.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryCustom.java
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ReadCountResponse.java
  src/main/resources/templates/chat/chat-rooms.html
Labels: ✨ Feature, 🎨 Design

#65 상대방과 대화시 실시간 읽음 가능하게 구현
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ChatMessageController.java
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ConnectRequest.java
  src/main/java/com/hermez/farrot/chat/chatmessage/controller/ConnectResponse.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomRequest.java
  src/main/resources/templates/chat/chat-room.html
Labels: ✨ Feature

#66 채팅js 업로드
  src/main/resources/static/js/chat/chat.js
Labels: ✨ Feature, 🎨 Design

#67 관리자 비활성화 페이지 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/member/admin-member-disable.html
  src/main/resources/templates/admin/member/admin-member.html
Labels: ✨ Feature, 🎨 Design

#68 관리자 실시간 상품 등록 갱신 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/resources/static/js/admin/findTop5Latest.js
  src/main/resources/templates/admin/chat/admin-chat.html
  src/main/resources/templates/admin/form/admin-form.html
Labels: ✨ Feature

#69 상품 상세 페이지 css 적용
  src/main/resources/templates/product/product-detail.html
Labels: 🎨 Design

#70 관리자 메인 Query 수정
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
Labels: 🐞 BugFix

#71 채팅 목록 디자인 변경
  src/main/resources/templates/chat/chat-rooms.html
Labels: 🎨 Design

#72 Feat/member/detail
  src/main/java/com/hermez/farrot/member/controller/MemberController.java
  src/main/java/com/hermez/farrot/member/entity/Member.java
  src/main/java/com/hermez/farrot/member/service/MemberService.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
  src/main/resources/templates/member/detail.html
Labels: 🐞 BugFix, ✨ Feature

#73 채팅 배경화면 지정
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/request/ChatRoomRequest.java
  src/main/java/com/hermez/farrot/chat/chatroom/dto/response/ReadCountResponse.java
  src/main/resources/templates/chat/chat-room.html
Labels: 🎨 Design

#75 관리자 비회원 기능 구현 및 html 수정
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepository.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/templates/admin/member/admin-member-detail.html
  src/main/resources/templates/admin/member/admin-member-disable.html
  src/main/resources/templates/admin/member/admin-member-trans-detail.html
  src/main/resources/templates/admin/member/admin-member.html
  src/main/resources/templates/admin/member/admin-report.html
  src/main/resources/templates/admin/product/admin-product-monthly.html
  src/main/resources/templates/admin/product/admin-product-today.html
  src/main/resources/templates/admin/product/admin-product-weekly.html
  src/main/resources/templates/admin/product/admin-product.html
Labels: ✨ Feature, 🎨 Design

#76 관리자 실시간 등록 차트 구현
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
Labels: ✨ Feature

#77 feat/build.gradle
  build.gradle
Labels: ⚙ Setting

#78 feat: 채팅 안 읽은 메시지 헤더에 알림 구현
  src/main/java/com/hermez/farrot/chat/chatmessage/repository/ChatMessageRepositoryImpl.java
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/chat/chatroom/repository/ChatRoomRepositoryCustom.java
  src/main/java/com/hermez/farrot/chat/chatroom/service/ChatRoomService.java
  src/main/resources/static/js/chat/chat.js
  src/main/resources/templates/layout/header.html
Labels: ✨ Feature, 🎨 Design

#79 Feat/member/detail
  src/main/java/com/hermez/farrot/member/controller/MemberController.java
  src/main/java/com/hermez/farrot/member/service/MemberService.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
Labels: 🔨 Refactor, 🥰 Accessibility, ⏳ Implementing

#80 fix : MemberUpdateRequest
  src/main/java/com/hermez/farrot/member/dto/request/MemberUpdateRequest.java
Labels: 🐞 BugFix

#81 채팅 메시지 이모지 추가
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
Labels: 🎨 Design

#82 상품 결제 코드 리팩토링
  src/main/java/com/hermez/farrot/payment/adapter/PaymentAdapter.java
  src/main/java/com/hermez/farrot/payment/adapter/impl/PaymentAdapterImpl.java
  src/main/java/com/hermez/farrot/payment/controller/PaymentController.java
  src/main/java/com/hermez/farrot/payment/dto/request/PaymentFormRequest.java
  src/main/java/com/hermez/farrot/payment/service/PaymentService.java
  src/main/java/com/hermez/farrot/payment/service/impl/PaymentServiceImpl.java
  src/main/java/com/hermez/farrot/product/controller/ProductController.java
  src/main/java/com/hermez/farrot/product/service/ProductService.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
  src/main/resources/templates/product/update-sell.html
Labels: 🔨 Refactor

#83 feat: 관리자 알림 구현 중
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/member/admin-member.html
Labels: 🚨 Conflict, ⏳ Implementing

#84 feature : MemberRepository
  src/main/java/com/hermez/farrot/member/repository/MemberRepository.java
Labels: ✨ Feature

#86 관리자 실시간 등록 차트 링크 연결
  src/main/resources/static/js/admin/findTop5Latest.js
  src/main/resources/templates/admin/form/admin-form.html
Labels: ✨ Feature

#87 관리자 알림 적용
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/dto/AdminNotificationRequest.java
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
  src/main/resources/templates/admin/member/admin-member.html
Labels: ✨ Feature, 📬 API

#88 wishlist 찜기능 구현
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
  src/main/java/com/hermez/farrot/product/controller/ProductController.java
  src/main/java/com/hermez/farrot/wishlist/controller/WishlistController.java
  src/main/java/com/hermez/farrot/wishlist/dto/WishlistDTO.java
  src/main/java/com/hermez/farrot/wishlist/dto/request/WishRequest.java
  src/main/java/com/hermez/farrot/wishlist/dto/response/WishResponse.java
  src/main/java/com/hermez/farrot/wishlist/entity/WishType.java
  src/main/java/com/hermez/farrot/wishlist/entity/Wishlist.java
  src/main/java/com/hermez/farrot/wishlist/repository/WishlistRepository.java
  src/main/java/com/hermez/farrot/wishlist/repository/WishlistRepositoryCustom.java
  src/main/java/com/hermez/farrot/wishlist/repository/WishlistRepositoryImpl.java
  src/main/java/com/hermez/farrot/wishlist/service/WishlistService.java
  src/main/java/com/hermez/farrot/wishlist/service/impl/WishlistServiceImpl.java
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/product/product-detail.html
  src/main/resources/templates/wishlist/wishlist.html
Labels: ✨ Feature, 🎨 Design

#89 Fix/member/detail update
  src/main/java/com/hermez/farrot/config/SecurityConfig.java
  src/main/java/com/hermez/farrot/member/controller/MemberController.java
  src/main/java/com/hermez/farrot/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/hermez/farrot/member/entity/Member.java
  src/main/java/com/hermez/farrot/member/service/MemberService.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
  src/main/resources/static/js/member/checkNewPassword.js
  src/main/resources/static/js/member/checkNickname.js
  src/main/resources/static/js/member/detailValidation.js
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/member/detail.html
Labels: 🐞 BugFix, ✨ Feature, ⏳ Implementing

#90 soldAt 컬럼 추가
  src/main/java/com/hermez/farrot/product/entity/Product.java
  src/main/java/com/hermez/farrot/product/service/ProductService.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
Labels: ✨ Feature

#91 관리자 회원&비회원 전환 구현
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
Labels: ✨ Feature

#93 관리자 상품 관리 페이지 버튼 제거
  src/main/resources/static/css/admin/chart.css
  src/main/resources/static/js/admin/todayTotalSales.js
  src/main/resources/static/js/admin/weeklyTotalSales.js
  src/main/resources/templates/admin/product/admin-product-monthly.html
  src/main/resources/templates/admin/product/admin-product-today.html
  src/main/resources/templates/admin/product/admin-product-weekly.html
  src/main/resources/templates/admin/product/admin-product.html
Labels: 🎨 Design

#94 채팅 관련 헤더 레이아웃
  src/main/java/com/hermez/farrot/wishlist/controller/WishlistController.java
  src/main/java/com/hermez/farrot/wishlist/service/WishlistService.java
  src/main/resources/templates/layout/header.html
Labels: 🎨 Design

#95 design 메시지 엔터 넣음
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
Labels: 🔨 Refactor, 🎨 Design

#96 Feat/member/detail image
  src/main/java/com/hermez/farrot/member/controller/MemberController.java
  src/main/java/com/hermez/farrot/member/dto/response/MemberImageResponse.java
  src/main/java/com/hermez/farrot/member/service/MemberService.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
  src/main/resources/static/default-member-image.png
  src/main/resources/static/js/member/imagePreview.js
  src/main/resources/templates/member/detail.html
Labels: 🐞 BugFix, ✨ Feature, 🎨 Design, 🥰 Accessibility

#97 관리자 메인 이번 주 카테고리별 조회수 통계
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/dto/response/AdminCategoryThisWeekTotalViewsResponse.java
  src/main/java/com/hermez/farrot/admin/repository/AdminRepositoryCustom.java
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/resources/static/js/admin/categoryViewMany.js
  src/main/resources/static/js/admin/monthlyTotalSales.js
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/product/admin-product-monthly.html
Labels: ✨ Feature

#98 wishlist 헤더 및 찜목록에 이미지 나오게 변경
  src/main/java/com/hermez/farrot/wishlist/dto/WishlistDTO.java
  src/main/java/com/hermez/farrot/wishlist/repository/WishlistRepositoryCustom.java
  src/main/java/com/hermez/farrot/wishlist/repository/WishlistRepositoryImpl.java
  src/main/java/com/hermez/farrot/wishlist/service/impl/WishlistServiceImpl.java
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/wishlist/wishlist.html
Labels: ✨ Feature, 🔨 Refactor, 🎨 Design

#100 chat/wishlist exception 처리
  src/main/java/com/hermez/farrot/chat/chatmessage/service/ChatMessageService.java
  src/main/java/com/hermez/farrot/chat/chatroom/controller/ChatRoomController.java
  src/main/java/com/hermez/farrot/common/GlobalExceptionHandler.java
  src/main/java/com/hermez/farrot/common/dto/ErrorResult.java
  src/main/java/com/hermez/farrot/member/exception/NotFoundMemberException.java
  src/main/java/com/hermez/farrot/notification/controller/NotificationController.java
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
  src/main/java/com/hermez/farrot/product/controller/ProductController.java
  src/main/java/com/hermez/farrot/wishlist/controller/WishlistController.java
  src/main/java/com/hermez/farrot/wishlist/exception/BadWishRequestException.java
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/product/product-detail.html
Labels: ✨ Feature, 🔨 Refactor

#101 괄호 수정
  src/main/java/com/hermez/farrot/common/GlobalExceptionHandler.java
Labels: 🐞 BugFix

#102 로고 이미지 업로드
  src/main/resources/static/img/core-img/farrot.png
Labels: 🎨 Design

#103 chat/wishlist 헤더 레이아웃 수정
  src/main/resources/templates/layout/header.html
Labels: 🎨 Design

#105 관리자 충돌 해결
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
Labels: 🐞 BugFix, 🚨 Conflict

#106 관리자 상품 가격 문제 해결
  src/main/java/com/hermez/farrot/admin/repository/impl/AdminRepositoryCustomImpl.java
Labels: 🐞 BugFix

#108 exception 중복 제거
  src/main/java/com/hermez/farrot/common/GlobalExceptionHandler.java
Labels: 🔨 Refactor

#109 헤더 푸터 수정
  src/main/resources/templates/layout/footer.html
  src/main/resources/templates/layout/header.html
Labels: 🎨 Design

#110 판매상품 버튼 디자인 수정
  src/main/resources/templates/product/member-products.html
Labels: 🎨 Design

#111 푸터 수정
  src/main/resources/templates/layout/footer.html
Labels: 🎨 Design

#112 인덱스에 들어갈 이미지 추가
  src/main/resources/static/img/bg-img/farrotimage.jpg
  src/main/resources/templates/index/index.html
Labels: 🎨 Design

#113 design wishlist 페이지 뷰 수정
  src/main/resources/templates/wishlist/wishlist.html
Labels: 🔨 Refactor, 🎨 Design

#115 찜 관련 헤더 및 찜목록 수정
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/wishlist/wishlist.html
Labels: 🎨 Design

#116 index 슬라이드 이미지 추가
  src/main/resources/static/img/bg-img/slide1.jpg
  src/main/resources/templates/index/index.html
Labels: 🎨 Design

#117 index 슬라이드 이미지 추가
  src/main/resources/static/img/bg-img/slide2.jpg
  src/main/resources/templates/index/index.html
Labels: 🎨 Design

#119 상품 신고 기능 구현
  src/main/java/com/hermez/farrot/report/Controller/ReportController.java
  src/main/java/com/hermez/farrot/report/dto/request/ReportRequest.java
  src/main/java/com/hermez/farrot/report/entity/Report.java
  src/main/java/com/hermez/farrot/report/entity/ReportType.java
  src/main/java/com/hermez/farrot/report/exception/DuplicateReportException.java
  src/main/java/com/hermez/farrot/report/repository/ReportRepository.java
  src/main/java/com/hermez/farrot/report/service/ReportService.java
  src/main/java/com/hermez/farrot/report/service/impl/ReportServiceImpl.java
  src/main/resources/templates/product/product-detail.html
Labels: ✨ Feature

#120 remove/member/OAuth
  src/main/java/com/hermez/farrot/member/oauth/OAuth2Contoller.java
  src/main/java/com/hermez/farrot/member/oauth/OAuth2SuccessHandler.java
  src/main/java/com/hermez/farrot/member/oauth/OAuth2UserInfo.java
Labels: 🗑️ Remove

#121 fix/member/report
  src/main/java/com/hermez/farrot/member/entity/Member.java
Labels: ⏳ Implementing

#122 notification 찜하면 판매자에게만 알림 가도록 수정
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
  src/main/java/com/hermez/farrot/wishlist/controller/WishlistController.java
Labels: 🐞 BugFix, 🔨 Refactor

#123 관리자 신고 구현중
  src/main/java/com/hermez/farrot/admin/Controller/AdminController.java
  src/main/java/com/hermez/farrot/admin/service/AdminService.java
  src/main/java/com/hermez/farrot/admin/service/impl/AdminServiceImpl.java
  src/main/java/com/hermez/farrot/report/repository/ReportRepository.java
  src/main/resources/templates/admin/admin-sidebar.html
  src/main/resources/templates/admin/form/admin-form.html
  src/main/resources/templates/admin/member/admin-report.html
Labels: ⏳ Implementing

#128 관리자 푸터 수정
  src/main/resources/templates/admin/chat/admin-chat.html
  src/main/resources/templates/admin/member/admin-member-detail.html
  src/main/resources/templates/admin/member/admin-member-disable.html
  src/main/resources/templates/admin/member/admin-member-trans-detail.html
  src/main/resources/templates/admin/member/admin-member.html
  src/main/resources/templates/admin/member/admin-report.html
  src/main/resources/templates/admin/product/admin-product-monthly.html
  src/main/resources/templates/admin/product/admin-product-today.html
  src/main/resources/templates/admin/product/admin-product-weekly.html
  src/main/resources/templates/admin/product/admin-product.html
Labels: 🎨 Design

#129 이미지 서비스 수정, 알림 수정
  src/main/java/com/hermez/farrot/image/repository/ImageRepository.java
  src/main/java/com/hermez/farrot/image/repository/ImageRepositoryCustom.java
  src/main/java/com/hermez/farrot/image/service/ImageService.java
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
  src/main/java/com/hermez/farrot/product/entity/Product.java
  src/main/java/com/hermez/farrot/product/service/impl/ProductServiceImpl.java
Labels: 🐞 BugFix, 🔨 Refactor

#130 notification 알림 토큰맵 리셋 추가
  src/main/java/com/hermez/farrot/notification/service/NotificationService.java
Labels: 🔨 Refactor

#132 관리자 리팩토링
  src/main/java/com/hermez/farrot/admin/controller/AdminController.java
  src/main/java/com/hermez/farrot/report/controller/ReportController.java
  src/main/resources/templates/admin/admin-sidebar.html
  src/main/resources/templates/admin/chat/admin-chat.html
  src/main/resources/templates/admin/form/admin-member-form.html
  src/main/resources/templates/admin/member/admin-member-detail.html
  src/main/resources/templates/admin/member/admin-member-disable.html
  src/main/resources/templates/admin/member/admin-member-trans-detail.html
  src/main/resources/templates/admin/member/admin-member.html
  src/main/resources/templates/admin/member/admin-report.html
Labels: 🔨 Refactor

#134 신고 비회원 처리
  src/main/java/com/hermez/farrot/report/controller/ReportController.java
Labels: 🐞 BugFix

#135 Fix/member/exception
  src/main/java/com/hermez/farrot/member/controller/MemberController.java
  src/main/java/com/hermez/farrot/member/dto/request/MemberCheckRequest.java
  src/main/java/com/hermez/farrot/member/repository/MemberRepository.java
  src/main/java/com/hermez/farrot/member/service/UserService.java
  src/main/resources/static/css/member/btn-custom.css
  src/main/resources/static/js/member/checkExPassword.js
  src/main/resources/static/js/member/checkNickname.js
  src/main/resources/static/js/member/regist-check-email-nickname.js
  src/main/resources/templates/member/detail.html
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/register.html
Labels: 🐞 BugFix

#136 design : naver ico
  src/main/resources/static/img/login-img/btn_naverlogin.png
  src/main/resources/static/img/login-img/member-naver-icon.png
Labels: 🎨 Design

#137 멤버 로그인, 회원가입 폼 수정
  src/main/resources/static/js/member/regist-check-email-nickname.js
  src/main/resources/templates/member/login.html
  src/main/resources/templates/member/register.html
Labels: 🎨 Design

#138 멤버 로그인 css 수정
  src/main/resources/templates/member/login.html
Labels: 🎨 Design

#139 fix : 회원등록 페이지
  src/main/resources/templates/member/register.html
Labels: 🐞 BugFix
